---
- name: Sendmail collection demo
  hosts: localhost
  tasks: 
    - name: Example playbook sending mail to root
      community.general.mail:
        subject: System {{ ansible_hostname }} has been successfully provisioned.

