---
- name: Create Redis service
  redhat.openshift.k8s:
    state: present
    namespace: automate-kube
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: redis
      spec:
        ports:
        - port: 6379
          protocol: TCP
          targetPort: 6379
        selector:
          vm.kubevirt.io/name: vm1

- name: Create Grafana service
  redhat.openshift.k8s:
    state: present
    namespace: automate-kube
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana
      spec:
        selector:
          vm.kubevirt.io/name: vm1
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 3000

- name: Create Grafana route
  redhat.openshift.k8s:
    service: grafana
    namespace: automate-kube
    tls:
      insecure_policy: redirect
    termination: edge
    hostname: <grafana route name>

- name: Create redis netpol
  redhat.openshift.k8s:
    state: present
    namespace: automate-kube
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: allow-redis
      spec:
        podSelector:
          matchLabels:
            vm.kubevirt.io/name: vm1
        ingress:
        - ports:
          - protocol: TCP
            port: 6379
